name: ride2online
description: Moto events
publish_to: 'none'
version: 0.2.12+12

environment:
  sdk: '>=3.0.0-12.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  adaptive_navigation: ^0.0.7
  collection: ^1.17.0
  path_to_regexp: ^0.4.0
  quiver: ^3.1.0
  url_launcher: ^6.1.7
  flutter_secure_storage: ^7.0.1
  http: ^0.13.5
  flutter_svg: ^1.1.6
  go_router: ^5.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: source-assets/app.png

flutter:
  uses-material-design: true
  assets:
    - assets/svg/logo.svg
    - assets/svg/logo_full.svg
    - assets/svg/logo_icon.svg

