name: ride2online
description: Moto events
publish_to: 'none'
version: 0.2.18+18

environment:
  sdk: '>=3.0.0-65.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  flutter_secure_storage: ^7.0.1
  http: ^0.13.5
  http_interceptor: ^2.0.0-beta.6
  flutter_svg: ^1.1.6
  go_router: ^6.0.0
  lottie: ^2.1.0
  flutter_multi_formatter: ^2.9.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: source-assets/app.png

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/svg/
    - assets/animation/
