name: ride2online
description: Moto events
publish_to: 'none'
version: 0.2.14+14

environment:
  sdk: '>=3.0.0-35.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  adaptive_navigation: ^0.0.7
  flutter_secure_storage: ^7.0.1
  http: ^0.13.5
  flutter_svg: ^1.1.6
  go_router: ^6.0.0
  flutter_verification_code: ^1.1.6
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
  simple_animations: ^5.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: source-assets/app.png

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/svg/
